<?php
/*$db_os->close(); 
$db_bq->close(); 
$db_bq->close(); 
$db_gb->close(); 
$db_gbs->close(); 
$db_fa->close(); 
$db_liq->close(); 
$db_pr->close(); 
$db_cont->close(); 
$db_cont1->close(); 
$db_or->close(); 
$db_pro->close(); 
$db_bk->close(); 
$db_in->close(); 
$db_mg->close(); 
$db_bcr->close(); 
$db_aj->close(); 
$db_ord->close(); 
*/
?>

