 LA DIRECCIÓN HTTP DE NUESTRO WEB SERVICE ES LA SIGUIENTE: 

 

http://borealtuc.dyndns.org:8080/Traditum/servlet/atraditum?wsdl

 

TANTO EL ARCHIVO DE CONSULTA (EL QUE ENVÍA EL PRESTADOR), COMO EL DE RESPUESTA, TIENEN PRÁCTICAMENTE LA MISMA ESTRUCTURA. 

 

COMO EJEMPLO, TE PASO EN COMO ADJUNTOS
?L?
OS ARCHIVOS ?TXT?
 REFERIDOS A LA AUTORIZACIÓN DE UNA CONSULTA MÉDICA. EN EL PRIMERO VA EL CÓDIGO XML QUE ENVÍA EL PRESTADOR Y EN EL SEGUNDO, EL CÓDIGO XML CORRESPONDIENTE A LA RESPUESTA DEL WEBSERVICE. 