<?php

$sql = "UPDATE detalle_orina SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE `detalle_urocultivo` SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_proteino SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_widal SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_coombs SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_curva SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_espermo SET  SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_bilirrubina SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_aglutininas SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_iono SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_clearence SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_hepatograma SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_antigeno SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_calcio SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_fosforo SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_proteinura SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_parasitologico SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_antibiograma SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_bacteriologico SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_iono_urinario SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_coagulograma SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE detalle_lipidograma SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
$sql = "UPDATE `detalle_referencia` SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);

$sql = "UPDATE `detalle` SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);

echo $sql = "UPDATE ordenes SET `nro_os` = '$nro_os' WHERE `nro_paciente` = $nro_paciente ";
$result11 = $db->Execute($sql);
